#!/bin/zsh
dcomp=()
wd(){
declare -A drs
conf="$HOME/.config/wd.conf"
while read -r line
do
    line=$(echo "$line"  | awk '/=/' ) 
    if [[ "$line" == "" ]]
    then continue
    fi
    name=$(echo "$line" | awk -F= '{print $1}')
    dpath=$(echo "$line" | awk -F= '{print $2}')
    drs["$name"]="$dpath"
done < "$conf"
for key value in ${(kv)drs}; do
    dcomp+=("$key")
done
dcomp=("${dcomp[@]//\"/}")
if [[ "$1" == "list" ]]; then 
    for key value in ${(kv)drs}; do
        echo "$key --> $value"
    done
elif [[ "$1" == "add" ]]; then
    echo "$2="'"'$PWD'"'"" >> $conf
elif [[ "$1" == "conf" ]]; then
     setsid nvim "$conf"
elif [[ "$1" == "dolphin" ]]; then
    if [[ -n "${drs["$2"]}" ]]; then
        eval "setsid dolphin $drs["$2"]$3";
    else
        echo "This dir doesn't exist in your config"
    fi
elif [[ "$1" == "kate" ]]; then
    if [[ -n "${drs["$2"]}" ]]; then
        eval "setsid kate $drs["$2"]$3";
    else
        echo "This dir doesn't exist in your config"
    fi
elif [[ "$1" == "ls" ]]; then
    if [[ -n "${drs["$2"]}" ]]; then
        eval "setsid ls $drs["$2"]$3";
    else
        echo "This dir doesn't exist in your config"
    fi
elif [[ "$1" == "nvim" ]]; then
    if [[ -n "${drs["$2"]}" ]]; then
    eval "setsid nvim $drs["$2"]$3";
    else
    echo "This dir doesn't exist in your config"
    fi
elif [[ "$1" == "code" ]]; then
    if [[ -n "${drs["$2"]}" ]]; then
    eval "setsid code $drs["$2"]$3";
    else
    echo "This dir doesn't exist in your config"
    fi
elif [[ -n "${drs["$1"]}" ]]; then
    eval "cd $drs["$1"]$2";
else 
    echo "Type <list> to list the avalible directories"
    echo "Type <conf> to open the config file in vim"
    echo "Type <add> follwed by the name to add the current working directory (pwd) to your list"
    echo "Don't use any of the above command as an entery name as they won't work"
fi
unset drs conf line name dpath key value
}
wd >> /dev/null
